version: '3'
services:
  db:
    build:
      context: ./mysql
    container_name: "dc-db-mysql"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    command: --innodb-use-native-aio=0
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  postgres:
    restart: always
    image: postgres:alpine
    container_name: "dc-db-postgres"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432

  redis:
    image: redis:alpine
    container_name: "dc-db-redis"
    ports: 
      - 16379:6379

  web:
    build:
      context: ./rails
    container_name: "dc-app-rails"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 13000:3000
    volumes:
      - ./rails/src:/app
