version: '3'
services:
  db:
    build:
      context: ./mysql
    container_name: "mysql"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    command: --innodb-use-native-aio=0
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  web:
    build:
      context: ./rails
    container_name: "rails"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 13000:3000
    volumes:
      - ./rails/src:/app
